### ISSUE TITLE
How to disable the write protection?

### ISSUE THREAD

**Issue by Anubuntu** [bq/aquaris-E4.5#2]
I can't write to /etc/apparmor/abstractions/dubs . It says it's a read only file system. How can I mount it with write permissions? The standard mount command doesn't seem to work

**Comment by john-mcaleely** [comment]
The filesystem is in general read only. This is a feature of Ubuntu on phones. Perhaps you have already found: http://developer.ubuntu.com/en/start/ubuntu-for-devices/

Asking questions on the ubuntu-phone mailing list should get answers.
