### ISSUE TITLE
Where is the zimage?

### ISSUE THREAD

**Issue by Pablito2020** [bq/aquaris-E4.5#3]
Hello,
I build the kernel but I can't find the zimage, Where is it?

Cheers.

**Comment by Kra1o5** [comment]
Hello @Pablito2020 ,

What version are you building?

Regards,

**Comment by eyakm1** [comment]
go to out/target/product/krillin
There wil be kernel_krillin.bin
This is a zImage

**Comment by Pablito2020** [comment]
Thanks eyakm1 ;) Finally I can find it

**Comment by eyakm1** [comment]
Closes bq/aquaris-E4.5#3

**Comment by Kra1o5** [comment]
Hello @Pablito2020 ,

With your permission I close the issue.

Greetings
