### ISSUE TITLE
No Root when Flash Kernel

### ISSUE THREAD

**Issue by Pablito2020** [bq/aquaris-E4.5#4]
When I compile the 3.10.54 kernel for the Aquaris E4.5 and I flash it to my device, I can't root it! I try with kingroot and says that y pone isn't compatible, I flash supersu with the recovery and my mobile stuck at bootanimation... It must be kernel problem, because with the stock kernel, It doesn't happen!

I make the kernel with the instructions of this repository..... So I don't know what I'm doing wrong.

**Comment by Pablito2020** [comment]
@Kra1o5 help please, more than a week and I can find the fix

**Comment by eyakm1** [comment]
What custom recovery did you installed?? You need to install to download and install TWRP from [https://dl.twrp.me/krillin/](url). Then install SU app from Google Play. It will update your SU binary from recovery

**Comment by eyakm1** [comment]
closed #4

**Comment by Pablito2020** [comment]
I use the latest twrp recovery @eyakm1

**Comment by Pablito2020** [comment]
Don't worry It was a selinux problem, must put it in permissive
I will close this issue
